import { CatalogoAceitesError } from "./aceitesCatalogo.errors";
import type { CatalogoAceiteGuardarResultado, CatalogoAceiteItem, CatalogoAceitesResumen, CatalogoSistemaRelacionado, CatalogoTipoEquipoImpacto } from "./aceitesCatalogo.types";
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
function invalid(message: string): never { throw new CatalogoAceitesError("RESPUESTA_INVALIDA", message); }
function id(value: unknown, field: string): number { if (typeof value !== "number" || !Number.isInteger(value) || value <= 0) return invalid(`${field} debe ser un ID positivo.`); return value; }
function count(value: unknown, field: string): number { if (typeof value !== "number" || !Number.isFinite(value) || value < 0) return invalid(`${field} debe ser no negativo.`); return value; }
function text(value: unknown, field: string): string { if (typeof value !== "string" || !value.trim()) return invalid(`${field} es obligatorio.`); return value.trim(); }
function timestamp(value: unknown): string | null { return typeof value === "string" && value.trim() && !Number.isNaN(Date.parse(value)) ? value : null; }
function mapSystem(value: unknown): CatalogoSistemaRelacionado { if (!isRecord(value)) return invalid("Sistema relacionado inválido."); return { id: id(value.id, "sistemas.id"), nombre: text(value.nombre, "sistemas.nombre"), cantidadEquipos: count(value.cantidad_equipos, "sistemas.cantidad_equipos") }; }
function mapEquipmentType(value: unknown): CatalogoTipoEquipoImpacto { if (!isRecord(value)) return invalid("Tipo de equipo inválido."); return { id: id(value.id, "impacto.tipos_equipo.id"), nombre: text(value.nombre, "impacto.tipos_equipo.nombre"), cantidadEquipos: count(value.cantidad_equipos, "impacto.tipos_equipo.cantidad_equipos") }; }
export function mapCatalogoAceiteItem(value: unknown): CatalogoAceiteItem {
  if (!isRecord(value) || !Array.isArray(value.sistemas) || !isRecord(value.impacto) || !Array.isArray(value.impacto.tipos_equipo)) return invalid("El aceite retornado es inválido.");
  if (typeof value.activo !== "boolean") return invalid("activo debe ser booleano.");
  return { id: id(value.id, "id"), nombre: text(value.nombre, "nombre"), activo: value.activo, creadoEn: timestamp(value.creado_en), actualizadoEn: timestamp(value.actualizado_en), sistemas: value.sistemas.map(mapSystem), impacto: { totalEquipos: count(value.impacto.total_equipos, "impacto.total_equipos"), totalAsignaciones: count(value.impacto.total_asignaciones, "impacto.total_asignaciones"), tiposEquipo: value.impacto.tipos_equipo.map(mapEquipmentType) } };
}
export function mapCatalogoAceitesListarResponse(value: unknown): { items: CatalogoAceiteItem[]; resumen: CatalogoAceitesResumen } { if (!isRecord(value) || value.ok !== true || !Array.isArray(value.items) || !isRecord(value.resumen)) return invalid("Listado inválido."); return { items: value.items.map(mapCatalogoAceiteItem), resumen: { total: count(value.resumen.total, "resumen.total"), activos: count(value.resumen.activos, "resumen.activos"), desactivados: count(value.resumen.desactivados, "resumen.desactivados") } }; }
export function mapCatalogoAceiteGuardarResponse(value: unknown): CatalogoAceiteGuardarResultado { if (!isRecord(value) || value.ok !== true || (value.operacion !== "creado" && value.operacion !== "actualizado") || (value.codigo !== "ACEITE_CREADO" && value.codigo !== "ACEITE_ACTUALIZADO")) return invalid("Guardado inválido."); return { operacion: value.operacion, codigo: value.codigo, mensaje: text(value.mensaje, "mensaje"), afectaEquipos: count(value.afecta_equipos, "afecta_equipos"), item: mapCatalogoAceiteItem(value.item) }; }
