export type CatalogoAceitesErrorCode = "AUTENTICACION_REQUERIDA" | "PAYLOAD_INVALIDO" | "REGISTRO_NO_ENCONTRADO" | "ACEITE_NOMBRE_REQUERIDO" | "ACEITE_NOMBRE_DUPLICADO" | "ACEITE_NO_ENCONTRADO" | "RESPUESTA_INVALIDA" | "TRANSPORTE" | "DESCONOCIDO";
const KNOWN: readonly CatalogoAceitesErrorCode[] = ["AUTENTICACION_REQUERIDA", "PAYLOAD_INVALIDO", "REGISTRO_NO_ENCONTRADO", "ACEITE_NOMBRE_REQUERIDO", "ACEITE_NOMBRE_DUPLICADO", "ACEITE_NO_ENCONTRADO"];
const MESSAGES: Record<CatalogoAceitesErrorCode, string> = {
  AUTENTICACION_REQUERIDA: "Tu sesión ya no es válida. Inicia sesión nuevamente.", PAYLOAD_INVALIDO: "No se pudieron validar los datos enviados.", REGISTRO_NO_ENCONTRADO: "El registro ya no existe o fue modificado.", ACEITE_NOMBRE_REQUERIDO: "Ingresa un nombre para mostrar.", ACEITE_NOMBRE_DUPLICADO: "Ya existe un aceite con ese nombre.", ACEITE_NO_ENCONTRADO: "El aceite ya no está disponible. Actualiza el listado.", RESPUESTA_INVALIDA: "La respuesta del catálogo no tiene el formato esperado.", TRANSPORTE: "No fue posible comunicarse con el catálogo.", DESCONOCIDO: "No se pudo guardar el aceite. Intenta nuevamente.",
};
export class CatalogoAceitesError extends Error { constructor(public readonly codigo: CatalogoAceitesErrorCode, message = MESSAGES[codigo]) { super(message); this.name = "CatalogoAceitesError"; } }
function stringify(value: unknown): string { if (typeof value === "string") return value; if (value instanceof Error) return value.message; if (typeof value === "object" && value !== null) { const record = value as Record<string, unknown>; return [record.code, record.codigo, record.message, record.details, record.hint].filter((part): part is string => typeof part === "string").join(" "); } return ""; }
export function normalizarCatalogoAceitesError(error: unknown, fallback: CatalogoAceitesErrorCode = "DESCONOCIDO"): CatalogoAceitesError { if (error instanceof CatalogoAceitesError) return error; const content = stringify(error); return new CatalogoAceitesError(KNOWN.find((code) => content.includes(code)) ?? fallback); }
export function mensajeCatalogoAceitesError(error: CatalogoAceitesError | null): string | null { return error?.message ?? null; }
