export type CatalogoSistemasErrorCode = "AUTENTICACION_REQUERIDA" | "PAYLOAD_INVALIDO" | "REGISTRO_NO_ENCONTRADO" | "SISTEMA_NOMBRE_REQUERIDO" | "SISTEMA_NOMBRE_DUPLICADO" | "SISTEMA_NO_ENCONTRADO" | "RESPUESTA_INVALIDA" | "TRANSPORTE" | "DESCONOCIDO";
const KNOWN: readonly CatalogoSistemasErrorCode[] = ["AUTENTICACION_REQUERIDA", "PAYLOAD_INVALIDO", "REGISTRO_NO_ENCONTRADO", "SISTEMA_NOMBRE_REQUERIDO", "SISTEMA_NOMBRE_DUPLICADO", "SISTEMA_NO_ENCONTRADO"];
const MESSAGES: Record<CatalogoSistemasErrorCode, string> = {
  AUTENTICACION_REQUERIDA: "Tu sesión ya no es válida. Inicia sesión nuevamente.", PAYLOAD_INVALIDO: "No se pudieron validar los datos enviados.", REGISTRO_NO_ENCONTRADO: "El registro ya no existe o fue modificado.", SISTEMA_NOMBRE_REQUERIDO: "Ingresa un nombre para mostrar.", SISTEMA_NOMBRE_DUPLICADO: "Ya existe un sistema con ese nombre.", SISTEMA_NO_ENCONTRADO: "El sistema ya no está disponible. Actualiza el listado.", RESPUESTA_INVALIDA: "La respuesta del catálogo no tiene el formato esperado.", TRANSPORTE: "No fue posible comunicarse con el catálogo.", DESCONOCIDO: "No se pudo guardar el sistema. Intenta nuevamente.",
};
export class CatalogoSistemasError extends Error { constructor(public readonly codigo: CatalogoSistemasErrorCode, message = MESSAGES[codigo]) { super(message); this.name = "CatalogoSistemasError"; } }
function stringify(value: unknown): string { if (typeof value === "string") return value; if (value instanceof Error) return value.message; if (typeof value === "object" && value !== null) { const record = value as Record<string, unknown>; return [record.code, record.codigo, record.message, record.details, record.hint].filter((part): part is string => typeof part === "string").join(" "); } return ""; }
export function normalizarCatalogoSistemasError(error: unknown, fallback: CatalogoSistemasErrorCode = "DESCONOCIDO"): CatalogoSistemasError { if (error instanceof CatalogoSistemasError) return error; const content = stringify(error); return new CatalogoSistemasError(KNOWN.find((code) => content.includes(code)) ?? fallback); }
export function mensajeCatalogoSistemasError(error: CatalogoSistemasError | null): string | null { return error?.message ?? null; }
