<script setup lang="ts">
import { computed, shallowRef } from 'vue'
import { Search, X } from 'lucide-vue-next'
import type { FiltroCodigoSugerencia } from '@/stores/dbequipos/engrase/filtrosEngrase.types'
const props=defineProps<{modelValue:string;sugerencias:FiltroCodigoSugerencia[];loading:boolean}>();const emit=defineEmits<{ 'update:modelValue':[string]; search:[string]; select:[FiltroCodigoSugerencia]; clear:[] }>();const open=shallowRef(false),active=shallowRef(-1);const listId='filtro-codigo-suggestions';const hasSuggestions=computed(()=>props.sugerencias.length>0)
function input(value:string){emit('update:modelValue',value);open.value=true;active.value=-1;emit('search',value)}function choose(item:FiltroCodigoSugerencia){emit('select',item);open.value=false}function keydown(event:KeyboardEvent){if(event.key==='Escape'){open.value=false;return}if(event.key==='ArrowDown'){event.preventDefault();active.value=Math.min(active.value+1,props.sugerencias.length-1)}if(event.key==='ArrowUp'){event.preventDefault();active.value=Math.max(active.value-1,0)}if(event.key==='Enter'&&active.value>=0){event.preventDefault();choose(props.sugerencias[active.value])}}
</script>
<template><div class="relative"><label class="filter-label" for="codigo-filtro">Buscar por código de filtro</label><div class="input-wrap"><Search class="input-icon" aria-hidden="true"/><input id="codigo-filtro" :value="modelValue" class="filter-input" role="combobox" :aria-expanded="open && hasSuggestions" :aria-controls="listId" aria-autocomplete="list" placeholder="Código original o equivalente" @focus="open=true" @input="input(($event.target as HTMLInputElement).value)" @keydown="keydown"/><button v-if="modelValue" type="button" class="clear" aria-label="Limpiar código" @click="emit('clear');open=false"><X class="w-4 h-4"/></button></div><div v-if="open && (hasSuggestions || loading)" :id="listId" class="suggestions" role="listbox" :aria-busy="loading"><p v-if="loading" class="suggestion-muted">Buscando códigos…</p><button v-for="(item,index) in sugerencias" :key="item.codigo" type="button" role="option" :aria-selected="active===index" class="suggestion" :class="{active:active===index}" @mousedown.prevent="choose(item)"><strong>{{item.codigo}}</strong><span>{{ item.esOriginal&&item.esEquivalente?'Original y equivalente':item.esOriginal?'Original':'Equivalente' }}</span></button></div></div></template>
<style scoped>.filter-label{display:block;margin-bottom:.45rem;font-size:.73rem;font-weight:800;color:#172554}.input-wrap{position:relative}.filter-input{width:100%;height:44px;border:1px solid #dbe4f0;border-radius:.7rem;padding:0 2.4rem;color:#172554;background:#fff}.filter-input:focus{outline:2px solid #2563eb;outline-offset:1px}.input-icon{position:absolute;left:.75rem;top:.72rem;width:18px;color:#5270a8}.filter-input{padding-left:2.35rem}.clear{position:absolute;right:.55rem;top:.55rem;color:#5270a8;padding:.2rem}.suggestions{position:absolute;z-index:20;top:calc(100% + .35rem);width:100%;max-height:16rem;overflow:auto;border:1px solid #dbe4f0;border-radius:.7rem;background:white;box-shadow:0 14px 30px #17255422}.suggestion{display:flex;width:100%;justify-content:space-between;padding:.7rem .85rem;text-align:left;font-size:.8rem;color:#172554}.suggestion:hover,.suggestion.active{background:#eff6ff}.suggestion span,.suggestion-muted{color:#64748b;font-size:.7rem}.suggestion-muted{padding:.7rem .85rem}</style>
