<script setup lang="ts">
import { Eraser, Plus, Search, SlidersHorizontal, X } from "lucide-vue-next";
import type { CatalogoAceiteEstado, CatalogoAceiteUso, CatalogoSistemaRelacionado } from "@/stores/dbequipos/engrase/catalogo/aceitesCatalogo.types";
const props = defineProps<{ busqueda:string; sistemaId:number|null; estado:CatalogoAceiteEstado; uso:CatalogoAceiteUso; sistemas:readonly CatalogoSistemaRelacionado[]; canClear:boolean }>();
const emit = defineEmits<{ updateBusqueda:[string];updateSistema:[number|null];updateEstado:[CatalogoAceiteEstado];updateUso:[CatalogoAceiteUso];openFilters:[];clear:[];create:[] }>();
const filterCount = () => Number(props.sistemaId !== null) + Number(props.estado !== "activos") + Number(props.uso !== "todos");
</script>
<template><div class="grid min-w-0 grid-cols-[1fr_44px] gap-2 sm:grid-cols-[minmax(230px,1fr)_auto_auto] lg:flex lg:flex-wrap">
  <div class="relative min-w-0 lg:min-w-[230px] lg:max-w-[380px] lg:flex-1"><label for="aceites-search" class="sr-only">Buscar aceite por nombre</label><Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" /><input id="aceites-search" :value="busqueda" type="search" autocomplete="off" placeholder="Buscar por nombre de aceite" class="min-h-11 w-full rounded-md border border-gray-300 bg-white pl-9 pr-11 text-base outline-none focus:border-main focus:ring-2 focus:ring-main/15 md:min-h-9 md:text-sm" @input="emit('updateBusqueda',($event.target as HTMLInputElement).value)" /><button v-if="busqueda" type="button" class="absolute right-0 top-0 grid min-h-11 min-w-11 cursor-pointer place-items-center rounded-r-md text-gray-500 hover:bg-gray-100 md:min-h-9 md:min-w-9" aria-label="Limpiar búsqueda" @click="emit('updateBusqueda','')"><X class="h-4 w-4" /></button></div>
  <button type="button" class="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-gray-300 bg-white px-3 text-sm font-semibold lg:hidden" :aria-label="`Abrir filtros, ${filterCount()} activos`" @click="emit('openFilters')"><SlidersHorizontal class="h-4 w-4" /><span class="hidden sm:inline">Filtros</span><span v-if="filterCount()" class="rounded-full bg-main px-1.5 text-xs text-white">{{ filterCount() }}</span></button>
  <label class="hidden lg:block lg:w-[175px]"><span class="sr-only">Sistema relacionado</span><select :value="sistemaId ?? ''" class="h-9 w-full cursor-pointer rounded-md border border-gray-300 bg-white px-3 text-sm" @change="emit('updateSistema',($event.target as HTMLSelectElement).value ? Number(($event.target as HTMLSelectElement).value) : null)"><option value="">Todos los sistemas</option><option v-for="item in sistemas" :key="item.id" :value="item.id">{{ item.nombre }}</option></select></label>
  <label class="hidden lg:block lg:w-[145px]"><span class="sr-only">Estado</span><select :value="estado" class="h-9 w-full cursor-pointer rounded-md border border-gray-300 bg-white px-3 text-sm" @change="emit('updateEstado',($event.target as HTMLSelectElement).value as CatalogoAceiteEstado)"><option value="activos">Activos</option><option value="desactivados">Desactivados</option><option value="todos">Todos</option></select></label>
  <label class="hidden lg:block lg:w-[140px]"><span class="sr-only">En uso</span><select :value="uso" class="h-9 w-full cursor-pointer rounded-md border border-gray-300 bg-white px-3 text-sm" @change="emit('updateUso',($event.target as HTMLSelectElement).value as CatalogoAceiteUso)"><option value="todos">Todos</option><option value="en-uso">En uso</option><option value="sin-uso">Sin uso</option></select></label>
  <button type="button" class="col-span-2 inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md bg-main px-3 text-sm font-semibold text-white hover:bg-main-light sm:col-span-1 lg:h-9 lg:min-h-0 lg:text-xs" @click="emit('create')"><Plus class="h-4 w-4" />Nuevo aceite</button>
  <button type="button" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-gray-300 bg-white px-3 text-sm font-semibold text-gray-600 sm:col-start-3 sm:row-start-1 lg:h-9 lg:min-h-0 lg:text-xs" :class="canClear ? 'cursor-pointer hover:bg-main/5 hover:text-main' : 'cursor-not-allowed opacity-50'" :disabled="!canClear" aria-label="Limpiar filtros" @click="emit('clear')"><Eraser class="h-4 w-4" /><span class="hidden lg:inline">Limpiar filtros</span></button>
</div></template>
