<script setup lang="ts">
import { Eraser, ListFilter, Plus, Search, X } from "lucide-vue-next";
import type { CatalogoSistemaEstado, CatalogoSistemaUso } from "@/stores/dbequipos/engrase/catalogo/sistemasCatalogo.types";
defineProps<{ busqueda: string; estado: CatalogoSistemaEstado; uso: CatalogoSistemaUso; canClear: boolean; activeFilterCount: number; canCreate: boolean }>();
const emit = defineEmits<{ updateBusqueda: [value:string]; updateEstado:[value:CatalogoSistemaEstado]; updateUso:[value:CatalogoSistemaUso]; openFilters:[]; clear:[]; create:[] }>();
const value = (event: Event): string => (event.target as HTMLInputElement | HTMLSelectElement).value;
</script>
<template><div class="grid gap-2 lg:grid-cols-[minmax(260px,420px)_minmax(150px,170px)_minmax(150px,170px)_auto_auto]">
  <div class="relative min-w-0"><label for="sistemas-search" class="sr-only">Buscar sistema por nombre</label><Search class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" aria-hidden="true"/><input id="sistemas-search" :value="busqueda" type="search" autocomplete="off" placeholder="Buscar por nombre de sistema" class="min-h-11 w-full rounded-md border border-gray-300 bg-white pl-9 pr-10 text-base outline-none focus:border-main focus:ring-2 focus:ring-main/15 md:min-h-9 md:text-sm" @input="emit('updateBusqueda',value($event))"/><button v-if="busqueda" type="button" class="absolute right-0 top-0 grid min-h-11 min-w-11 cursor-pointer place-items-center rounded-r-md text-gray-500 hover:bg-gray-100 md:min-h-9 md:min-w-9" aria-label="Limpiar búsqueda" @click="emit('updateBusqueda','')"><X class="h-4 w-4"/></button></div>
  <select :value="estado" aria-label="Estado" class="hidden h-9 cursor-pointer rounded-md border border-gray-300 bg-white px-3 text-sm outline-none focus:border-main lg:block" @change="emit('updateEstado',value($event) as CatalogoSistemaEstado)"><option value="activos">Activos</option><option value="desactivados">Desactivados</option><option value="todos">Todos</option></select>
  <select :value="uso" aria-label="En uso" class="hidden h-9 cursor-pointer rounded-md border border-gray-300 bg-white px-3 text-sm outline-none focus:border-main lg:block" @change="emit('updateUso',value($event) as CatalogoSistemaUso)"><option value="todos">Todos</option><option value="en-uso">En uso</option><option value="sin-uso">Sin uso</option></select>
  <div class="grid grid-cols-[1fr_44px] gap-2 lg:hidden"><button type="button" class="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md border border-gray-300 bg-white px-3 text-sm font-semibold text-main" @click="emit('openFilters')"><ListFilter class="h-4 w-4"/>Filtros<span v-if="activeFilterCount" class="rounded-full bg-main px-1.5 py-0.5 text-[10px] text-white">{{ activeFilterCount }}</span></button><button type="button" class="grid h-11 w-11 place-items-center rounded-md border border-gray-300 bg-white" :class="canClear ? 'cursor-pointer text-main' : 'cursor-not-allowed text-gray-300'" :disabled="!canClear" aria-label="Limpiar filtros" @click="emit('clear')"><Eraser class="h-4 w-4"/></button></div>
  <button v-if="canCreate" type="button" class="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md bg-main px-3 text-sm font-semibold text-white shadow-sm hover:bg-main-light md:min-h-9 md:text-xs" @click="emit('create')"><Plus class="h-4 w-4"/>Nuevo sistema</button>
  <button type="button" class="hidden h-9 items-center gap-2 rounded-md border border-gray-300 bg-white px-3 text-xs font-semibold lg:inline-flex" :class="canClear ? 'cursor-pointer text-main hover:bg-main/5' : 'cursor-not-allowed text-gray-400 opacity-50'" :disabled="!canClear" @click="emit('clear')"><Eraser class="h-4 w-4"/>Limpiar filtros</button>
</div></template>
