<script setup lang="ts">
import { ArrowDown, ArrowUp, ArrowUpDown, ChevronRight, Cog } from "lucide-vue-next";
import SistemaEstadoBadge from "./SistemaEstadoBadge.vue";
import { formatNumber } from "@/stores/dbequipos/engrase/catalogo/sistemasCatalogo.helpers";
import type { CatalogoSistemaItem, CatalogoSistemaSortKey, CatalogoSortDirection } from "@/stores/dbequipos/engrase/catalogo/sistemasCatalogo.types";
const props = defineProps<{ items: readonly CatalogoSistemaItem[]; selectedId:number|null; sortKey:CatalogoSistemaSortKey; sortDirection:CatalogoSortDirection }>();
const emit = defineEmits<{ select:[item:CatalogoSistemaItem, trigger:HTMLElement]; sort:[key:CatalogoSistemaSortKey] }>();
function ariaSort(key:CatalogoSistemaSortKey):"ascending"|"descending"|"none" { return props.sortKey !== key ? "none" : props.sortDirection === "asc" ? "ascending" : "descending"; }
const sortIcon = (key:CatalogoSistemaSortKey) => props.sortKey === key ? (props.sortDirection === "asc" ? ArrowUp : ArrowDown) : ArrowUpDown;
</script>
<template><div class="hidden overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm md:block"><table class="w-full table-fixed text-left text-xs" role="grid" aria-label="Sistemas"><colgroup><col class="w-12"/><col/><col class="w-40"/><col class="w-56"/><col class="w-10"/></colgroup><thead class="bg-gray-50 text-gray-600"><tr class="h-9 border-b border-gray-200"><th/><th :aria-sort="ariaSort('nombre')"><button type="button" class="inline-flex h-9 cursor-pointer items-center gap-1.5 px-3 font-semibold" @click="emit('sort','nombre')">Nombre<component :is="sortIcon('nombre')" class="h-3.5 w-3.5"/></button></th><th :aria-sort="ariaSort('estado')"><button type="button" class="inline-flex h-9 cursor-pointer items-center gap-1.5 px-3 font-semibold" @click="emit('sort','estado')">Estado<component :is="sortIcon('estado')" class="h-3.5 w-3.5"/></button></th><th :aria-sort="ariaSort(sortKey === 'asignaciones' ? 'asignaciones' : 'equipos')"><div class="flex"><button type="button" class="inline-flex h-9 cursor-pointer items-center gap-1 px-3 font-semibold" title="Ordenar por equipos" @click="emit('sort','equipos')">Resumen de uso<component :is="sortIcon('equipos')" class="h-3.5 w-3.5"/></button><button type="button" class="sr-only" @click="emit('sort','asignaciones')">Ordenar por total de asignaciones</button></div></th><th><span class="sr-only">Abrir detalles</span></th></tr></thead><tbody><tr v-for="item in items" :key="item.id" tabindex="0" class="h-14 cursor-pointer border-b border-gray-100 hover:bg-main/5 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-main" :class="selectedId===item.id ? 'bg-main/7 shadow-[inset_3px_0_0_var(--color-main)]' : ''" :aria-selected="selectedId===item.id" @click="emit('select',item,$event.currentTarget as HTMLElement)" @keydown.enter="emit('select',item,$event.currentTarget as HTMLElement)" @keydown.space.prevent="emit('select',item,$event.currentTarget as HTMLElement)"><td class="px-3"><span class="grid h-7 w-7 place-items-center rounded-md bg-main/7 text-main"><Cog class="h-4 w-4"/></span></td><td class="truncate px-3 text-sm font-semibold text-main">{{ item.nombre }}</td><td class="px-3"><SistemaEstadoBadge :activo="item.activo"/></td><td class="px-3"><dl class="grid grid-cols-[1fr_auto] gap-x-3 text-xs text-gray-600"><dt>Equipos</dt><dd class="font-semibold tabular-nums">{{ formatNumber(item.impacto.totalEquipos) }}</dd><dt>Total asignaciones</dt><dd class="font-semibold tabular-nums">{{ formatNumber(item.impacto.totalAsignaciones) }}</dd></dl></td><td class="px-2 text-main"><ChevronRight class="h-4 w-4"/></td></tr></tbody></table></div></template>
